//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
	public static HashMap<String,String> h= new HashMap<String,String>();
	
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( DeclStatement() )*
    * f1 -> ( Statement() )*
    * f2 -> PrintStatment()
    * f3 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      return _ret;
   }

   /**
    * f0 -> IntDecl()
    *       | BoolDecl()
    */
   public R visit(DeclStatement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <INT>
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(IntDecl n) {
      R _ret=null;
      String a ; 
      n.f0.accept(this);
	a=n.f1.f0.toString();
//System.out.println(a);
      n.f2.accept(this);
      h.put(a,"int");
      return _ret;
   }

   /**
    * f0 -> <BOOL>
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(BoolDecl n) {
      R _ret=null;
	String a ; 
      n.f0.accept(this);
      a=n.f1.f0.toString();
      n.f2.accept(this);
      h.put(a,"bool");
	return _ret;
   }

   /**
    * f0 -> <PRINT>
    * f1 -> Expression()
    */
   public R visit(PrintStatment n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> AssignmentStatement()
    */
   public R visit(Statement n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n) {
      R _ret=null;
	String a,b;
      a=n.f0.accept(this).toString();
      n.f1.accept(this);
      b=n.f2.accept(this).toString();
      n.f3.accept(this);
	if(!a.equals(b)){
	System.out.println("type error");
	System.exit(0);}
      return _ret;
   }

   /**
    * f0 -> PlusExpression()
    *       | MinusExpression()
    *       | GTExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n) {
      R _ret=null;
     _ret=(R)n.f0.accept(this).toString();
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n) {
      R _ret=null;
	String a,b;
      a=n.f0.accept(this).toString();
      n.f1.accept(this);
      b=n.f2.accept(this).toString();
	if(!a.equals("int")||!b.equals("int")){
	System.out.println("type error");
	System.exit(0);}
	_ret=(R)("int");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n) {
      R _ret=null;
      String a,b;
      a=n.f0.accept(this).toString();
      n.f1.accept(this);
      b=n.f2.accept(this).toString();
	if(!a.equals("int")||!b.equals("int")){
	System.out.println("type error");
	System.exit(0);}
	_ret=(R)("int");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ">"
    * f2 -> PrimaryExpression()
    */
   public R visit(GTExpression n) {
      R _ret=null;
      String a,b;
      a=n.f0.accept(this).toString();
      n.f1.accept(this);
      b=n.f2.accept(this).toString();
	if(!a.equals("int")||!b.equals("int")){
	System.out.println("type error");
	System.exit(0);}
	_ret=(R)("bool");
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | Identifier()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n) {
      R _ret=null;
      _ret=(R)n.f0.accept(this).toString();
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n) {
      R _ret=null;
      n.f0.accept(this);
      _ret= (R)("int");
	return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n) {
      R _ret=null;
//System.out.println(n.f0.toString());
	if(h.containsKey(n.f0.toString()))
      {_ret = (R)h.get(n.f0.toString());
     //System.out.println((String)_ret);
	}
	else{
	System.out.println("type error");
	System.exit(0);}
      n.f0.accept(this);
	
	
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n) {
      R _ret=null;
      n.f0.accept(this);
      _ret=(R)n.f1.accept(this).toString();
      n.f2.accept(this);
      return _ret;
   }

}
